# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/moseley',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/moseley',
                'lib_path': 'moseley'},
  'syms': { 'moseley.mplot': { 'moseley.mplot.XFluo': ('mplot.html#xfluo', 'moseley/mplot.py'),
                               'moseley.mplot.XFluo.__init__': ('mplot.html#xfluo.__init__', 'moseley/mplot.py'),
                               'moseley.mplot.XFluo.plot': ('mplot.html#xfluo.plot', 'moseley/mplot.py'),
                               'moseley.mplot._colorize': ('mplot.html#_colorize', 'moseley/mplot.py'),
                               'moseley.mplot._draw_box': ('mplot.html#_draw_box', 'moseley/mplot.py'),
                               'moseley.mplot.make_ptable': ('mplot.html#make_ptable', 'moseley/mplot.py'),
                               'moseley.mplot.moseley_law': ('mplot.html#moseley_law', 'moseley/mplot.py'),
                               'moseley.mplot.moseley_plot': ('mplot.html#moseley_plot', 'moseley/mplot.py'),
                               'moseley.mplot.ptable_plot': ('mplot.html#ptable_plot', 'moseley/mplot.py')}}}
