# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"my_sum": "00_physics.ipynb"}

modules = ["physics.py"]

doc_url = "https://fligt.github.io/mosely/"

git_url = "https://github.com/fligt/mosely/tree/master/"

def custom_doc_links(name): return None
